[project]
name = "quantumshield"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CodeByG14", email = "nairgirish2004@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jsonschema>=4.26.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
quantumshield = "quantumshield:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
